# Just to avoid warnings in the cmdline log, can just remove  the first line here about the 
# 'version: 3.8', as  modern Docker Compose ignores it anyhow:
# version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: servutils_mcp_grafana_container
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # Note of .yml files only docker-compose.yml by default auto reads from .env. Don't try this by default in other .ymls!
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}" # host_port:container_port. For easy configuring and consistency just specifying conainer_port to be same. If conflicts you could change it to some other hardcoded value.
    depends_on:
      - loki
      - prometheus
    volumes:
      # If not using examples, comment these out. Coupled to example metrics service's datasources and dashboards.
      - ./example_metrics_emitter/provisioning/grafana/datasources:/etc/grafana/provisioning/datasources #Grafana automatically knows how to pick these up locally to make available as dashboard with the file names in urls, and as available datasources
      - ./example_metrics_emitter/provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards #Grafana automatically knows how to pick these up locally to make available as dashboard with the file names in urls, and as available datasources
      - ./grafana-data:/var/lib/grafana  # persistent Grafana DB, this line here just to avoid warns in cmd line log

  prometheus:
    image: prom/prometheus:latest
    container_name: servutils_mcp_prometheus_container
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki: # Note: don't use 'latest' somehow latest may not be compatible currently:
    image: grafana/loki:2.9.0
    container_name: servutils_mcp_loki_container
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml

  # mcp-grafana aka 'Grafana MCP (Server)'  (Official Grafana product for expose your grafana server to LLMs: https://github.com/grafana/mcp-grafana)
  grafanamcp:
    image: mcp/grafana
    container_name: servutils_mcp_grafanamcp_container
    ports:
      - "${GRAFANA_MCP_PORT}:${GRAFANA_MCP_PORT}"
    environment:
      - GRAFANA_URL=${GRAFANA_URL}
      - GRAFANA_SERVICE_ACCOUNT_TOKEN=${GRAFANA_SERVICE_ACCOUNT_TOKEN}
    restart: unless-stopped
    depends_on:
      - prometheus
      - grafana
    command: -t streamable-http -address :${GRAFANA_MCP_PORT}
    healthcheck:
      test: ["CMD", "curl", "-f", "${GRAFANA_MCP_URL}"]
      interval: 10s
      timeout: 5s
      retries: 5

  example_metrics_emitter_servicename: # note, to work, coupled to grafana service's volumes adding the datasources and dashboards.
    build:
      context: ./example_metrics_emitter
    container_name: example_metrics_container
    ports:
      - "${EXAMPLE_METRICS_EMITTER_PORT}:${EXAMPLE_METRICS_EMITTER_PORT}"  # host_port:container_port

# Just to have an explicit predictable name to find (rather than relying on Docker's auto-gen'd name that'd be same as containing folder):
networks:
  default:
    name: servutils_mcp_grafana
