# Just to avoid warnings in the cmdline log, can just remove  the first line here about the 
# 'version: 3.8', as  modern Docker Compose ignores it anyhow:
# version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: ${PROJECT_PREFIX}_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # Note of .yml files only docker-compose.yml by default auto reads from .env. Don't try this by default in other .ymls!
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}" # host_port:container_port. For easy configuring and consistency just specifying conainer_port to be same. If conflicts you could change it to some other hardcoded value.
    depends_on:
      - loki
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: servutils_mcp_grafana_prometheus_container
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - prometheus-storage:/prometheus
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.0 # Note: don't use 'latest' somehow latest may not be compatible currently.
    container_name: ${PROJECT_PREFIX}_loki
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"

  # grafana-mcp-server (official grafana packaged server)
  mcp_server:
    image: grafana/mcp:latest
    container_name: servutils_mcp_grafana_mcp_server_container
    ports:
      - "${GRAFANA_MCP_PORT}:${GRAFANA_MCP_PORT}"
    environment:
      - GRAFANA_URL=${GRAFANA_URL}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
      - grafana

  example_metrics_emitter_servicename:
    build: ./example-metrics_emitter
    container_name: example_metrics_container
    ports:
      - "${EXAMPLE_METRICS_EMITTER_PORT}:${EXAMPLE_METRICS_EMITTER_PORT}"  # host_port:container_port
    depends_on:
      - prometheus
      - grafana

volumes:
  grafana-storage:
  prometheus-storage:

# Just to have an explicit predictable name to find (rather than relying on Docker's auto-gen'd name that'd be same as containing folder):
networks:
  default:
    name: ${PROJECT_PREFIX}
