# Just to avoid warnings in the cmdline log, can just remove  the first line here about the 
# 'version: 3.8', as  modern Docker Compose ignores it anyhow:
# version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: ${PROJECT_PREFIX}_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}" # host_port:container_port. For easy configuring and consistency just specifying conainer_port to be same. If conflicts you could change it to some other hardcoded value.
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROJECT_PREFIX}_prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - prometheus-storage:/prometheus
      - ./grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./example-metrics-logos_emitter/prometheus.yml:/etc/prometheus/example-metrics-logs_emitter.yml
  #command: --config.file=/etc/prometheus/prometheus.yml --config.file=/etc/prometheus/example-metrics-logs_emitter.yml

  loki:
    image: grafana/loki:latest
    container_name: ${PROJECT_PREFIX}_loki
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"

  grafana-mcp-server:
    image: grafana/mcp:latest
    container_name: ${PROJECT_PREFIX}_mcp-server
    ports:
      - "${GRAFANA_MCP_PORT}:${GRAFANA_MCP_PORT}"
    environment:
      - GRAFANA_URL=${GRAFANA_URL}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - grafana

  example-metrics-logs-emitter:
    build: ./example-metrics-logs_emitter
    container_name: ${PROJECT_PREFIX}_example-metrics
    ports:
      - "${EXAMPLE_METRICS_EMITTER_PORT}:${EXAMPLE_METRICS_EMITTER_PORT}"  # host_port:container_port

volumes:
  grafana-storage:
  prometheus-storage:

# Just to have an explicit predictable name to find (rather than relying on Docker's auto-gen'd name that'd be same as containing folder):
networks:
  default:
    name: ${PROJECT_PREFIX}
