apiVersion: 1
datasources:
  # This name is so grafana has can reference this in the dashboard panels its creates (see create_example_dashboard.sh)
  - name: Prometheus_main
    type: prometheus
    access: proxy
    url: http://servutils_mcp_grafana_prometheus_container:9090 # Coupled to .env values
    isDefault: true