global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['${PROJECT_PREFIX}_prometheus:${PROMETHEUS_PORT}']  # container hostname + internal port
  - file_sd_configs:
    - files:
      - /etc/prometheus/example-metrics_emitter/prometheus.yml # coupled to docker-compose.yml's volumes