# Configures prometheus' scrape jobs
# Note Including by default the sample metrics is done via the ../grafana/prometheus/prometheus.yml, and docker-compose.yml (coupled)

# Omit the 'global' and 'scrape_configs' here as this file is simply loaded by the main ../grafana/prometheus/prometheus.yml
#global:
#  scrape_interval: 5s
#scrape_configs:
  - job_name: 'example-metrics'
    static_configs:
      - targets: ['${PROJECT_PREFIX}_example-metrics:${EXAMPLE_METRICS_EMITTER_PORT}']