# Configures prometheus' scrape jobs
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'example-metrics'
    static_configs:
      - targets: ['servutils_mcp_grafana_example-metrics:${EXAMPLE_METRICS_PORT}']